### ISSUE TITLE
Add Tuitions Saving Tracker

### ISSUE THREAD

**Issue by cncarey** [cncarey/PirateSoftwareJam15#14]
- [x] add progress bar to track progress
- [x] update progress bar when coins change
- [x] display win on full
